--------------------------------------------------------
--  File created - понедельник-марта-04-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AUTO_PERSONNEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence AUTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##NIKOLASTOJKOSKI"."AUTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence JOURNAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##NIKOLASTOJKOSKI"."JOURNAL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROUTES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##NIKOLASTOJKOSKI"."ROUTES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table AUTO
--------------------------------------------------------

  CREATE TABLE "C##NIKOLASTOJKOSKI"."AUTO" 
   (	"ID" NUMBER, 
	"NUM" VARCHAR2(20 BYTE), 
	"COLOR" VARCHAR2(20 BYTE), 
	"MARK" VARCHAR2(20 BYTE), 
	"PERSONNEL_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AUTO_PERSONNEL
--------------------------------------------------------

  CREATE TABLE "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL" 
   (	"ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"FATHER_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOURNAL
--------------------------------------------------------

  CREATE TABLE "C##NIKOLASTOJKOSKI"."JOURNAL" 
   (	"ID" NUMBER, 
	"TIME_OUT" TIMESTAMP (3), 
	"TIME_IN" TIMESTAMP (3), 
	"AUTO_ID" NUMBER, 
	"ROUTE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROUTES
--------------------------------------------------------

  CREATE TABLE "C##NIKOLASTOJKOSKI"."ROUTES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into C##NIKOLASTOJKOSKI.AUTO
SET DEFINE OFF;
Insert into C##NIKOLASTOJKOSKI.AUTO (ID,NUM,COLOR,MARK,PERSONNEL_ID) values ('1','13535','red','Toyota','1');
Insert into C##NIKOLASTOJKOSKI.AUTO (ID,NUM,COLOR,MARK,PERSONNEL_ID) values ('2','13542','black','BMW','2');
REM INSERTING into C##NIKOLASTOJKOSKI.AUTO_PERSONNEL
SET DEFINE OFF;
Insert into C##NIKOLASTOJKOSKI.AUTO_PERSONNEL (ID,FIRST_NAME,LAST_NAME,FATHER_NAME) values ('1','Nikola','Stojkoski','Spiro');
Insert into C##NIKOLASTOJKOSKI.AUTO_PERSONNEL (ID,FIRST_NAME,LAST_NAME,FATHER_NAME) values ('2','Chin','Van','Thanh');
Insert into C##NIKOLASTOJKOSKI.AUTO_PERSONNEL (ID,FIRST_NAME,LAST_NAME,FATHER_NAME) values ('3','Petrov','Petr','Petrovich');
REM INSERTING into C##NIKOLASTOJKOSKI.JOURNAL
SET DEFINE OFF;
Insert into C##NIKOLASTOJKOSKI.JOURNAL (ID,TIME_OUT,TIME_IN,AUTO_ID,ROUTE_ID) values ('3',to_timestamp('04.03.19 11:00:00,886000000','DD.MM.RR HH24:MI:SSXFF'),to_timestamp('04.03.19 15:00:00,094000000','DD.MM.RR HH24:MI:SSXFF'),'1','1');
Insert into C##NIKOLASTOJKOSKI.JOURNAL (ID,TIME_OUT,TIME_IN,AUTO_ID,ROUTE_ID) values ('4',to_timestamp('04.03.19 08:00:00,112000000','DD.MM.RR HH24:MI:SSXFF'),to_timestamp('04.03.19 10:00:00,816000000','DD.MM.RR HH24:MI:SSXFF'),'2','2');
REM INSERTING into C##NIKOLASTOJKOSKI.ROUTES
SET DEFINE OFF;
Insert into C##NIKOLASTOJKOSKI.ROUTES (ID,NAME) values ('1','route1');
Insert into C##NIKOLASTOJKOSKI.ROUTES (ID,NAME) values ('2','route2');
Insert into C##NIKOLASTOJKOSKI.ROUTES (ID,NAME) values ('3','route3');
--------------------------------------------------------
--  DDL for Index AUTO_PERSONNEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL_PK" ON "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NIKOLASTOJKOSKI"."AUTO_PK" ON "C##NIKOLASTOJKOSKI"."AUTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JOURNAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NIKOLASTOJKOSKI"."JOURNAL_PK" ON "C##NIKOLASTOJKOSKI"."JOURNAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROUTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##NIKOLASTOJKOSKI"."ROUTES_PK" ON "C##NIKOLASTOJKOSKI"."ROUTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger AUTO_PERSONNEL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL_TRG" 
BEFORE INSERT ON AUTO_PERSONNEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT AUTO_PERSONNEL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##NIKOLASTOJKOSKI"."AUTO_TRG" 
BEFORE INSERT ON AUTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT AUTO_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##NIKOLASTOJKOSKI"."AUTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JOURNAL_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##NIKOLASTOJKOSKI"."JOURNAL_TRG" 
BEFORE INSERT ON JOURNAL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT JOURNAL_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##NIKOLASTOJKOSKI"."JOURNAL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROUTES_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##NIKOLASTOJKOSKI"."ROUTES_TRG" 
BEFORE INSERT ON ROUTES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ROUTES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##NIKOLASTOJKOSKI"."ROUTES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO
--------------------------------------------------------

  ALTER TABLE "C##NIKOLASTOJKOSKI"."AUTO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##NIKOLASTOJKOSKI"."AUTO" ADD CONSTRAINT "AUTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO_PERSONNEL
--------------------------------------------------------

  ALTER TABLE "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL" ADD CONSTRAINT "AUTO_PERSONNEL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JOURNAL
--------------------------------------------------------

  ALTER TABLE "C##NIKOLASTOJKOSKI"."JOURNAL" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##NIKOLASTOJKOSKI"."JOURNAL" ADD CONSTRAINT "JOURNAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROUTES
--------------------------------------------------------

  ALTER TABLE "C##NIKOLASTOJKOSKI"."ROUTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##NIKOLASTOJKOSKI"."ROUTES" ADD CONSTRAINT "ROUTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTO
--------------------------------------------------------

  ALTER TABLE "C##NIKOLASTOJKOSKI"."AUTO" ADD CONSTRAINT "FK_AUTO_AUTO_PERSONNEL" FOREIGN KEY ("PERSONNEL_ID")
	  REFERENCES "C##NIKOLASTOJKOSKI"."AUTO_PERSONNEL" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JOURNAL
--------------------------------------------------------

  ALTER TABLE "C##NIKOLASTOJKOSKI"."JOURNAL" ADD CONSTRAINT "FK_JOURNAL_ROUTES" FOREIGN KEY ("ROUTE_ID")
	  REFERENCES "C##NIKOLASTOJKOSKI"."ROUTES" ("ID") ENABLE;
  ALTER TABLE "C##NIKOLASTOJKOSKI"."JOURNAL" ADD CONSTRAINT "FK_JOURNAL_AUTO" FOREIGN KEY ("AUTO_ID")
	  REFERENCES "C##NIKOLASTOJKOSKI"."AUTO" ("ID") ENABLE;
